"""Native Streamlit theme derived from the design tokens.

This is the single definition of the ``[theme]`` and ``[theme.sidebar]`` sections that every
``.streamlit/config.toml`` in the course workspace carries. It does not import Streamlit:
it only produces plain values and TOML text, so it runs anywhere.

Every emitted key exists in Streamlit 1.47, the compatibility floor. Alert colors
(``redColor``, ``blueBackgroundColor`` and similar) and ``metricValueFontSize`` arrived after
1.47, so they are not emitted; ``styles.py`` covers the metric gap with CSS.

Color role choices:
* ``primaryColor`` is the accessible CTA orange, because Streamlit draws primary buttons as
  white text on ``primaryColor`` and also uses it for focus and active widget states.
* ``secondaryBackgroundColor`` is white: Streamlit fills input widgets with it, so inputs
  read as white fields with a strong outline on the light gray app background.
* ``borderColor`` is the strong border so input outlines meet the 3:1 non-text minimum;
  dataframe grid lines use the lighter decorative border.
"""
from __future__ import annotations

from .tokens import (
    COLORS,
    FONT_FAMILY_MONO,
    FONT_FAMILY_SANS,
    HEADINGS,
    RADII,
    TYPOGRAPHY,
)
from .version import KIT_VERSION

STREAMLIT_MIN_VERSION = "1.47"
STREAMLIT_REQUIREMENT = "streamlit>=1.47,<2"

ThemeValue = str | int | bool | list[str] | list[int]


def _px(value: int) -> str:
    return f"{value}px"


def streamlit_theme() -> dict[str, dict[str, ThemeValue]]:
    """Return the theme as ``{section: {key: value}}`` in a fixed, deterministic order."""
    main: dict[str, ThemeValue] = {
        "base": "light",
        "primaryColor": COLORS.action_primary_bg,
        "backgroundColor": COLORS.app_background,
        "secondaryBackgroundColor": COLORS.surface_primary,
        "textColor": COLORS.text_body,
        "linkColor": COLORS.brand_orange_strong,
        "linkUnderline": True,
        "borderColor": COLORS.border_strong,
        "showWidgetBorder": True,
        "showSidebarBorder": True,
        "baseRadius": _px(RADII.standard),
        "buttonRadius": _px(RADII.standard),
        "font": FONT_FAMILY_SANS,
        "headingFont": FONT_FAMILY_SANS,
        "codeFont": FONT_FAMILY_MONO,
        "baseFontSize": TYPOGRAPHY.body.size_px,
        "baseFontWeight": TYPOGRAPHY.body.weight,
        "headingFontSizes": [_px(size) for size in HEADINGS.sizes_px],
        "headingFontWeights": list(HEADINGS.weights),
        "codeFontSize": _px(TYPOGRAPHY.code.size_px),
        "codeBackgroundColor": COLORS.surface_secondary,
        "dataframeBorderColor": COLORS.border,
        "dataframeHeaderBackgroundColor": COLORS.surface_secondary,
    }
    sidebar: dict[str, ThemeValue] = {
        "backgroundColor": COLORS.surface_primary,
        "secondaryBackgroundColor": COLORS.surface_primary,
        "headingFontSizes": [_px(size) for size in HEADINGS.sidebar_sizes_px],
        "headingFontWeights": list(HEADINGS.sidebar_weights),
    }
    return {"theme": main, "theme.sidebar": sidebar}


def _toml_value(value: ThemeValue) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return "[" + ", ".join(_toml_value(item) for item in value) + "]"


def render_config_toml() -> str:
    """Render the full ``.streamlit/config.toml`` text shared by every launch context."""
    lines = [
        f"# Generated by csc8830-ui {KIT_VERSION}. Do not edit by hand.",
        "# Regenerate with: python scripts/vendor.py sync (in the csc8830-ui repository).",
        f"# Requires {STREAMLIT_REQUIREMENT}. Contains no secrets.",
    ]
    for section, values in streamlit_theme().items():
        lines += ["", f"[{section}]"]
        lines += [f"{key} = {_toml_value(value)}" for key, value in values.items()]
    return "\n".join(lines) + "\n"
