"""Vendor the canonical kit into the course workspace, or check that copies match it.

Usage, from the csc8830-ui repository root (the workspace defaults to its parent directory):

    python scripts/vendor.py check                 # report parity for every target, exit 1 on drift
    python scripts/vendor.py check module3         # one target
    python scripts/vendor.py sync                  # copy the package and write config.toml files
    python scripts/vendor.py sync --force          # also replace locally edited kit files

What it writes, and nothing else:
* every file of ``src/csc8830_ui/`` (recursively, ``*.py`` only, caches excluded), byte for
  byte, into each target's design package
* ``_kit_manifest.json`` in that package, recording which files the kit owns
* the generated ``.streamlit/config.toml`` in each launch context

Ownership: the manifest lists every kit-owned file by relative path with its SHA-256. A file
in a design package that the manifest does not list is unknown and is never overwritten or
deleted. A copy vendored before manifests existed (KIT_VERSION 0.2.0) has no manifest; its
files are treated as owned when their paths match canonical kit files.

Safety rules:
* refuses when a design package holds unknown files
* refuses to replace an owned file that was edited after vendoring, unless ``--force``
* refuses to downgrade a target that carries a newer KIT_VERSION, unless ``--allow-downgrade``
* refuses to overwrite a config.toml that this script did not generate
* refuses to vendor content containing em or en dash characters (Module 3 rule)
* removes owned files that the current kit no longer ships, and nothing else
The vendored copies use only relative imports, so assignments never need this repository at
runtime.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = REPO_ROOT / "src" / "csc8830_ui"
sys.path.insert(0, str(REPO_ROOT / "src"))

from csc8830_ui.theme import render_config_toml  # noqa: E402
from csc8830_ui.version import KIT_VERSION  # noqa: E402

KIT_NAME = "csc8830-ui"
MANIFEST_NAME = "_kit_manifest.json"
CONFIG_HEADER = "# Generated by csc8830-ui"
PROHIBITED_DASHES = (chr(0x2013), chr(0x2014))
_IGNORED_DIRS = {"__pycache__"}
_IGNORED_FILES = {".DS_Store"}
_VERSION_RE = re.compile(r'^KIT_VERSION = "(\d+\.\d+\.\d+)"$', re.MULTILINE)


@dataclass(frozen=True)
class Target:
    """One vendored copy: a design package directory plus the launch context it serves."""

    name: str
    repo_dir: str  # relative to the workspace
    package_dir: str  # relative to repo_dir
    config: bool = True  # whether repo_dir is a launch context needing config.toml


TARGETS: tuple[Target, ...] = (
    Target("module2", "Module_2", "src/module2/webapp/design"),
    Target("module3", "Module_3", "src/module3/webapp/design"),
    Target("module4", "Module_4", "src/module4/webapp/design"),
    Target("module5_6", "Module_5-6", "src/module5_6/webapp/design"),
    Target("root-dashboard", ".", "dashboard/design"),
    Target("deploy-dashboard", "csc8830-dashboard", "dashboard/design"),
)


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _version_tuple(version: str) -> tuple[int, ...]:
    return tuple(int(part) for part in version.split("."))


def _walk(root: Path) -> list[str]:
    """Relative POSIX paths of every file under ``root``, caches excluded, sorted."""
    paths = []
    for path in root.rglob("*"):
        rel = path.relative_to(root)
        if path.is_file() and not (set(rel.parts) & _IGNORED_DIRS) and path.name not in _IGNORED_FILES:
            paths.append(rel.as_posix())
    return sorted(paths)


def canonical_files() -> dict[str, bytes]:
    """The kit's package files by relative path, read from the canonical source."""
    return {rel: (PACKAGE_DIR / rel).read_bytes() for rel in _walk(PACKAGE_DIR) if rel.endswith(".py")}


def manifest_text(files: dict[str, bytes]) -> str:
    """Deterministic ownership manifest for a set of kit files."""
    body = {
        "kit": KIT_NAME,
        "kit_version": KIT_VERSION,
        "files": {rel: _sha(data) for rel, data in sorted(files.items())},
    }
    return json.dumps(body, indent=2, sort_keys=True) + "\n"


def _read_manifest(package: Path) -> dict | None:
    path = package / MANIFEST_NAME
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {"invalid": True}
    return data if isinstance(data, dict) else {"invalid": True}


def _vendored_version(package: Path) -> str | None:
    version_file = package / "version.py"
    if not version_file.is_file():
        return None
    match = _VERSION_RE.search(version_file.read_text(encoding="utf-8"))
    return match.group(1) if match else None


@dataclass
class PackageState:
    """What is currently in a target design package, classified by ownership."""

    present: list[str] = field(default_factory=list)  # every file except the manifest
    owned: set[str] = field(default_factory=set)
    unknown: list[str] = field(default_factory=list)
    edited: list[str] = field(default_factory=list)  # owned files changed after vendoring
    manifest: dict | None = None
    version: str | None = None


def inspect_package(package: Path, expected: dict[str, bytes]) -> PackageState:
    """Classify the files of one design package against the canonical kit."""
    state = PackageState()
    if not package.is_dir():
        return state
    state.present = [rel for rel in _walk(package) if rel != MANIFEST_NAME]
    state.manifest = _read_manifest(package)
    state.version = _vendored_version(package)
    recorded: dict[str, str] = {}
    if state.manifest and not state.manifest.get("invalid"):
        recorded = dict(state.manifest.get("files", {}))
        state.owned = set(recorded)
    else:
        # Legacy copy without a manifest: own only paths the canonical kit also has.
        state.owned = {rel for rel in state.present if rel in expected}
    state.unknown = [rel for rel in state.present if rel not in state.owned]
    for rel in sorted(state.owned & set(state.present)):
        data = (package / rel).read_bytes()
        if rel in recorded:
            changed = _sha(data) != recorded[rel]
        else:
            # Legacy: only a same-version copy can be compared reliably.
            changed = state.version == KIT_VERSION and data != expected.get(rel)
        if changed:
            state.edited.append(rel)
    return state


def check_target(workspace: Path, target: Target) -> list[str]:
    """Return human-readable problems for one target; empty means in parity."""
    repo = workspace / target.repo_dir
    if not repo.is_dir():
        return [f"repository directory missing: {repo}"]
    package = repo / target.package_dir
    expected = canonical_files()
    problems: list[str] = []
    if not package.is_dir():
        problems.append(f"design package not vendored: {package}")
    else:
        state = inspect_package(package, expected)
        if state.version != KIT_VERSION:
            problems.append(f"KIT_VERSION {state.version} != canonical {KIT_VERSION}")
        if state.manifest is None:
            problems.append(f"missing ownership manifest {MANIFEST_NAME}")
        elif (package / MANIFEST_NAME).read_text(encoding="utf-8") != manifest_text(expected):
            problems.append(f"{MANIFEST_NAME} differs from the canonical kit")
        problems += [f"unknown file not owned by the kit: {rel}" for rel in state.unknown]
        problems += [f"owned file edited after vendoring: {rel}" for rel in state.edited]
        for rel in sorted(state.owned - set(expected)):
            if rel in state.present:
                problems.append(f"stale kit file no longer shipped: {rel}")
        for rel, data in expected.items():
            path = package / rel
            if not path.is_file():
                problems.append(f"missing file: {rel}")
            elif path.read_bytes() != data and rel not in state.edited:
                problems.append(f"content differs: {rel}")
    if target.config:
        config = repo / ".streamlit" / "config.toml"
        if not config.is_file():
            problems.append("missing .streamlit/config.toml")
        elif config.read_text(encoding="utf-8") != render_config_toml():
            problems.append(".streamlit/config.toml differs from the generated theme")
    return problems


def _remove_emptied_dirs(start: Path, package: Path) -> None:
    """Remove directories left holding nothing but caches, walking up to the package root."""
    directory = start
    while directory != package and directory.is_dir():
        entries = list(directory.iterdir())
        if any(entry.name not in _IGNORED_DIRS for entry in entries):
            return
        for cache in entries:
            shutil.rmtree(cache)
        directory.rmdir()
        directory = directory.parent


def sync_target(
    workspace: Path, target: Target, *, force: bool, allow_downgrade: bool = False
) -> list[str]:
    """Copy the kit into one target. Returns refusal reasons; empty means written.

    All checks run before anything is written, so a refused target is left untouched.
    """
    repo = workspace / target.repo_dir
    if not repo.is_dir():
        return [f"repository directory missing: {repo}"]
    package = repo / target.package_dir
    expected = canonical_files()
    config_path = repo / ".streamlit" / "config.toml"
    state = inspect_package(package, expected)

    refusals: list[str] = []
    if state.manifest and state.manifest.get("invalid"):
        refusals.append(f"{MANIFEST_NAME} is not valid JSON; fix or remove it by hand")
    if state.version and _version_tuple(state.version) > _version_tuple(KIT_VERSION) and not allow_downgrade:
        refusals.append(f"target has newer KIT_VERSION {state.version}; refusing to downgrade")
    if state.unknown:
        refusals.append(f"unknown files not owned by the kit: {', '.join(state.unknown)}")
    if state.edited and not force:
        refusals.append(f"owned files edited after vendoring: {', '.join(state.edited)} (use --force)")
    if target.config and config_path.is_file():
        if not config_path.read_text(encoding="utf-8").startswith(CONFIG_HEADER):
            refusals.append(f"{config_path} was not generated by this kit; refusing to overwrite")
    if refusals:
        return refusals

    for rel, data in expected.items():
        dest = package / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
    for rel in sorted(state.owned - set(expected)):
        stale = package / rel
        if stale.is_file():
            stale.unlink()
            _remove_emptied_dirs(stale.parent, package)
    (package / MANIFEST_NAME).write_text(manifest_text(expected), encoding="utf-8")
    if target.config:
        config_path.parent.mkdir(exist_ok=True)
        config_path.write_text(render_config_toml(), encoding="utf-8")
    return []


def assert_dash_free() -> None:
    """Refuse to vendor anything that would break the Module 3 punctuation rule."""
    files = canonical_files()
    texts = {rel: data.decode("utf-8") for rel, data in files.items()}
    texts["config.toml"] = render_config_toml()
    texts[MANIFEST_NAME] = manifest_text(files)
    for name, text in texts.items():
        if any(ch in text for ch in PROHIBITED_DASHES):
            raise SystemExit(f"refusing to vendor: em or en dash found in {name}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", choices=["check", "sync"])
    parser.add_argument("targets", nargs="*", help="target names (default: all)")
    parser.add_argument("--workspace", type=Path, default=REPO_ROOT.parent)
    parser.add_argument("--force", action="store_true", help="replace locally edited kit files")
    parser.add_argument("--allow-downgrade", action="store_true", help="vendor over a newer kit")
    args = parser.parse_args(argv)

    by_name = {t.name: t for t in TARGETS}
    unknown = [name for name in args.targets if name not in by_name]
    if unknown:
        parser.error(f"unknown targets {unknown}; choose from {sorted(by_name)}")
    selected = [by_name[name] for name in args.targets] or list(TARGETS)
    workspace = args.workspace.resolve()

    print(f"{KIT_NAME} KIT_VERSION {KIT_VERSION} ({len(canonical_files())} files), workspace {workspace}")
    failed = False
    if args.command == "sync":
        assert_dash_free()
    for target in selected:
        if args.command == "sync":
            refusals = sync_target(
                workspace, target, force=args.force, allow_downgrade=args.allow_downgrade
            )
            if refusals:
                failed = True
                print(f"REFUSED  {target.name}: " + "; ".join(refusals))
                continue
        problems = check_target(workspace, target)
        failed = failed or bool(problems)
        print(("OK       " if not problems else "MISMATCH ") + target.name)
        for problem in problems:
            print(f"         - {problem}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
