"""Vendor the canonical kit into the course workspace, or check that copies match it.

Usage, from the csc8830-ui repository root (the workspace defaults to its parent directory):

    python scripts/vendor.py check                 # report parity for every target, exit 1 on drift
    python scripts/vendor.py check module3         # one target
    python scripts/vendor.py sync                  # copy package files and config.toml files
    python scripts/vendor.py sync --force          # also overwrite same-version local edits

What it writes, and nothing else:
* every ``src/csc8830_ui/*.py`` file, byte for byte, into each target's design package
* the generated ``.streamlit/config.toml`` into each launch context

Safety rules:
* refuses to downgrade a target that carries a newer KIT_VERSION
* refuses to overwrite a same-version copy that was edited locally, unless ``--force``
* refuses when a design package holds extra ``.py`` files the kit does not own
* refuses to overwrite a config.toml that this script did not generate
* refuses to vendor content containing em or en dash characters (Module 3 rule)
The vendored copies use only relative imports, so assignments never need this repository at
runtime.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = REPO_ROOT / "src" / "csc8830_ui"
sys.path.insert(0, str(REPO_ROOT / "src"))

from csc8830_ui.theme import render_config_toml  # noqa: E402
from csc8830_ui.version import KIT_VERSION  # noqa: E402

CONFIG_HEADER = "# Generated by csc8830-ui"
PROHIBITED_DASHES = (chr(0x2013), chr(0x2014))
_VERSION_RE = re.compile(r'^KIT_VERSION = "(\d+\.\d+\.\d+)"$', re.MULTILINE)


@dataclass(frozen=True)
class Target:
    """One vendored copy: a design package directory plus the launch context it serves."""

    name: str
    repo_dir: str  # relative to the workspace
    package_dir: str  # relative to repo_dir
    config: bool = True  # whether repo_dir is a launch context needing config.toml


TARGETS: tuple[Target, ...] = (
    Target("module2", "Module_2", "src/module2/webapp/design"),
    Target("module3", "Module_3", "src/module3/webapp/design"),
    Target("module4", "Module_4", "src/module4/webapp/design"),
    Target("module5_6", "Module_5-6", "src/module5_6/webapp/design"),
    Target("root-dashboard", ".", "dashboard/design"),
    Target("deploy-dashboard", "csc8830-dashboard", "dashboard/design"),
)


def _version_tuple(version: str) -> tuple[int, ...]:
    return tuple(int(part) for part in version.split("."))


def canonical_files() -> dict[str, bytes]:
    """The kit's package files by name, read from the canonical source."""
    return {p.name: p.read_bytes() for p in sorted(PACKAGE_DIR.glob("*.py"))}


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:12]


def _vendored_version(package: Path) -> str | None:
    version_file = package / "version.py"
    if not version_file.is_file():
        return None
    match = _VERSION_RE.search(version_file.read_text(encoding="utf-8"))
    return match.group(1) if match else None


def check_target(workspace: Path, target: Target) -> list[str]:
    """Return human-readable problems for one target; empty means in parity."""
    problems: list[str] = []
    repo = workspace / target.repo_dir
    if not repo.is_dir():
        return [f"repository directory missing: {repo}"]
    package = repo / target.package_dir
    expected = canonical_files()
    if not package.is_dir():
        problems.append(f"design package not vendored: {package}")
    else:
        version = _vendored_version(package)
        if version != KIT_VERSION:
            problems.append(f"KIT_VERSION {version} != canonical {KIT_VERSION}")
        present = {p.name for p in package.glob("*.py")}
        for name in sorted(present - set(expected)):
            problems.append(f"extra file not owned by the kit: {name}")
        for name, data in expected.items():
            path = package / name
            if not path.is_file():
                problems.append(f"missing file: {name}")
            elif path.read_bytes() != data:
                problems.append(f"content differs: {name} ({_sha(path.read_bytes())} != {_sha(data)})")
    if target.config:
        config = repo / ".streamlit" / "config.toml"
        if not config.is_file():
            problems.append("missing .streamlit/config.toml")
        elif config.read_text(encoding="utf-8") != render_config_toml():
            problems.append(".streamlit/config.toml differs from the generated theme")
    return problems


def sync_target(workspace: Path, target: Target, *, force: bool) -> list[str]:
    """Copy the kit into one target. Returns refusal reasons; empty means written."""
    repo = workspace / target.repo_dir
    if not repo.is_dir():
        return [f"repository directory missing: {repo}"]
    package = repo / target.package_dir
    expected = canonical_files()
    config_path = repo / ".streamlit" / "config.toml"

    refusals: list[str] = []
    if package.is_dir():
        version = _vendored_version(package)
        if version and _version_tuple(version) > _version_tuple(KIT_VERSION):
            refusals.append(f"target has newer KIT_VERSION {version}; refusing to downgrade")
        extras = sorted({p.name for p in package.glob("*.py")} - set(expected))
        if extras:
            refusals.append(f"extra files not owned by the kit: {', '.join(extras)}")
        edited = [
            name for name, data in expected.items()
            if (package / name).is_file() and (package / name).read_bytes() != data
        ]
        if version == KIT_VERSION and edited and not force:
            refusals.append(f"same-version copy edited locally: {', '.join(edited)} (use --force)")
    if target.config and config_path.is_file():
        if not config_path.read_text(encoding="utf-8").startswith(CONFIG_HEADER):
            refusals.append(f"{config_path} was not generated by this kit; refusing to overwrite")
    if refusals:
        return refusals

    package.mkdir(parents=True, exist_ok=True)
    for name, data in expected.items():
        (package / name).write_bytes(data)
    if target.config:
        config_path.parent.mkdir(exist_ok=True)
        config_path.write_text(render_config_toml(), encoding="utf-8")
    return []


def _assert_dash_free() -> None:
    texts = {name: data.decode("utf-8") for name, data in canonical_files().items()}
    texts["config.toml"] = render_config_toml()
    for name, text in texts.items():
        if any(ch in text for ch in PROHIBITED_DASHES):
            raise SystemExit(f"refusing to vendor: em or en dash found in {name}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", choices=["check", "sync"])
    parser.add_argument("targets", nargs="*", help="target names (default: all)")
    parser.add_argument("--workspace", type=Path, default=REPO_ROOT.parent)
    parser.add_argument("--force", action="store_true", help="overwrite same-version local edits")
    args = parser.parse_args(argv)

    by_name = {t.name: t for t in TARGETS}
    unknown = [name for name in args.targets if name not in by_name]
    if unknown:
        parser.error(f"unknown targets {unknown}; choose from {sorted(by_name)}")
    selected = [by_name[name] for name in args.targets] or list(TARGETS)
    workspace = args.workspace.resolve()

    print(f"csc8830-ui KIT_VERSION {KIT_VERSION}, workspace {workspace}")
    failed = False
    if args.command == "sync":
        _assert_dash_free()
    for target in selected:
        if args.command == "sync":
            refusals = sync_target(workspace, target, force=args.force)
            if refusals:
                failed = True
                print(f"REFUSED  {target.name}: " + "; ".join(refusals))
                continue
        problems = check_target(workspace, target)
        failed = failed or bool(problems)
        print(("OK       " if not problems else "MISMATCH ") + target.name)
        for problem in problems:
            print(f"         - {problem}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
